#!/system/bin/sh
if [ -e /sys/class/misc/gpu_clock_control/gpu_control ]; then
	echo "160 267 267" > /sys/class/misc/gpu_clock_control/gpu_control;
	echo "85% 50% 100% 50%" > /sys/class/misc/gpu_clock_control/gpu_control;
	#echo "800000 950000 950000" > /sys/devices/virtual/misc/gpu_voltage_control/gpu_control;
fi;
#if [ -e  /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table ]; then
	#echo "1400 1300 1175 1075 975 850 825 825 " > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table;
#fi;
